Repository DevSimpleQuiz/Frontend, pull requests merged in 2024-09, with the labels that each got.

#47 [#46] 일반 퀴즈 UI 디자인 변경
  src/pages/Quiz.tsx
Labels: design

#43 [#42] 랭킹 api 수정
  src/api/rank.api.ts
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankCard.tsx
  src/components/common/rank/RankError.tsx
  src/hooks/useAuth.ts
  src/hooks/useRank.ts
  src/models/rank.model.ts
  src/pages/Rank.tsx
Labels: fix

#50 [#45] 랭킹페이지 분리
  src/App.tsx
  src/api/rank.api.ts
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankCard.tsx
  src/hooks/useRank.ts
  src/models/rank.model.ts
  src/pages/Home.tsx
  src/pages/InfiniteQuiz.tsx
  src/pages/Rank.tsx
Labels: feat, fix

#52 [#49] 마이페이지
  src/assets/myPageImg/Vector-1.svg
  src/assets/myPageImg/Vector-2.svg
  src/assets/myPageImg/Vector-3.svg
  src/assets/myPageImg/Vector.svg
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankError.tsx
  src/hooks/useAuth.ts
  src/hooks/useRank.ts
  src/models/rank.model.ts
  src/pages/MyPage.tsx
  src/pages/Rank.tsx
Labels: feat

#54 [#53] home성능개선
  src/components/common/IconCard.tsx
  src/components/common/banner/Banner.tsx
  src/pages/Home.tsx
Labels: refact

#55 [#51] 전체랭킹 및 페이지네이션
  src/api/rank.api.ts
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankCard.tsx
  src/components/common/rank/RankTable.tsx
  src/components/common/rank/UnAuthorizedRank.tsx
  src/components/layout/Layout.tsx
  src/constants/allRankersDummy.ts
  src/hooks/useAuth.ts
  src/hooks/useRank.ts
  src/models/rank.model.ts
  src/pages/Home.tsx
  src/pages/Rank.tsx
  src/styles/theme.ts
Labels: feat, style
