Repository DevSimpleQuiz/Frontend, pull requests merged in 2024-07, with the labels that each got.

#9 [#7] 레이아웃 컴포넌트 구현 및 라우터 설정
  src/App.tsx
  src/components/common/Header.tsx
  src/components/layout/Layout.tsx
Labels: feat, style

#13 #3 메인페이지
  src/App.tsx
  src/assets/bannerImg/Banner1.svg
  src/assets/bannerImg/Banner2.svg
  src/assets/bannerImg/Banner3.svg
  src/assets/bannerImg/Banner4.svg
  src/assets/bannerImg/Banner5.svg
  src/assets/bannerImg/Banner6.svg
  src/assets/bannerImg/Banner7.svg
  src/assets/bannerImg/Banner8.svg
  src/assets/btnImg/infinite 1.svg
  src/assets/btnImg/quiz 1.svg
  src/assets/btnImg/ranking 1.svg
  src/assets/logo/DevSimpleQuizLogo.svg
  src/components/common/Error.tsx
  src/components/common/IconCard.tsx
  src/components/common/banner/Banner.tsx
  src/pages/Home.tsx
  src/pages/Quiz.tsx
  src/pages/Ranking.tsx
Labels: feat, style

#17 [#2] 회원가입 페이지 구현 (api 연결 x)
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/FormWrapper.tsx
  src/models/user.model.ts
  src/pages/Join.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: feat, style

#18 [#15] 로그인 페이지 구현 (api 연결 x)
  src/App.tsx
  src/components/common/FormWrapper.tsx
  src/components/common/Header.tsx
  src/context/AuthContext.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
Labels: feat, style

#22 [#15] 로그인 및 회원가입 api 연동, 쿠키로 token 받아오기
  src/App.tsx
  src/api/auth.api.ts
  src/api/http.ts
  src/components/common/Header.tsx
  src/hooks/useAuth.ts
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/store/authStore.ts
Labels: feat

#25 #24 로그아웃 api
  src/api/auth.api.ts
  src/components/common/Header.tsx
  src/hooks/useAuth.ts
  src/store/authStore.ts
Labels: feat

#29 [#27] 회원가입시 아이디 중복체크 필수 기능
  src/App.tsx
  src/api/auth.api.ts
  src/api/http.ts
  src/components/common/Header.tsx
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankCard.tsx
  src/hooks/useAuth.ts
  src/models/rank.model.ts
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/Rank.tsx
  src/pages/Ranking.tsx
  src/store/authStore.ts
Labels: fix

#31 [#14] 퀴즈 결과 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/quiz.api.ts
  src/components/common/ConfettiComponent.tsx
  src/hooks/useSaveQuizResult.ts
  src/models/quiz.model.ts
  src/pages/Quiz.tsx
  src/pages/QuizResult.tsx
Labels: feat, style

#33 [#21] 랭킹 조회 페이지
  src/api/auth.api.ts
  src/api/http.ts
  src/api/rank.api.ts
  src/components/common/rank/NearRank.tsx
  src/components/common/rank/RankCard.tsx
  src/components/common/rank/UnAuthorizedRank.tsx
  src/hooks/useAuth.ts
  src/hooks/useRank.ts
  src/models/rank.model.ts
  src/pages/Rank.tsx
Labels: feat, style

#34 #12 마이페이지
  src/App.tsx
  src/api/myPage.api.ts
  src/api/quiz.api.ts
  src/hooks/useQuizzes.ts
  src/hooks/useUsers.ts
  src/pages/MyPage.tsx
  src/pages/Quiz.tsx
Labels: feat, style

#37 [#32] 메인페이지 스타일
  src/assets/bannerImg/Banner1.svg
  src/assets/bannerImg/Banner2.svg
  src/assets/bannerImg/Banner3.svg
  src/assets/bannerImg/Banner4.svg
  src/assets/bannerImg/Banner5.svg
  src/assets/bannerImg/Banner6.svg
  src/assets/bannerImg/Banner7.svg
  src/assets/bannerImg/Banner8.svg
  src/components/common/IconCard.tsx
  src/components/common/banner/Banner.tsx
  src/pages/Home.tsx
Labels: style

#40 [#38] 헤더 최초 접근 오류
  src/components/common/Header.tsx
  src/store/authStore.ts
Labels: fix

#39 style : 지금까지 푼 문제 컬럼명 수정
  src/models/myPage.model.ts
  src/pages/MyPage.tsx
  src/pages/Quiz.tsx
Labels: style

#41 [#32] style, 로고, 타이틀 수정
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/logo.svg
Labels: style
